#!/bin/sh
### BEGIN INIT INFO
# Provides:          firewall
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: pare-feu iptables (INPUT drop sauf ssh + lo)
### END INIT INFO

IPT=/usr/sbin/iptables

start() {
    $IPT -F
    $IPT -P INPUT DROP
    $IPT -P FORWARD DROP
    $IPT -P OUTPUT ACCEPT
    $IPT -A INPUT -i lo -j ACCEPT
    $IPT -A INPUT -p tcp --dport 22 -j ACCEPT
}

stop() {
    $IPT -F
    $IPT -P INPUT ACCEPT
    $IPT -P FORWARD ACCEPT
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) stop; start ;;
    status) $IPT -L -n ;;
    *) echo "usage: $0 {start|stop|restart|status}"; exit 1 ;;
esac
